version: "3"

services:
  traccar-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: traccar-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
      - ./datas:/var/lib/mysql
      - ./datas:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        ipv4_address: 192.168.55.9

  strapi-db:
    image: elestio/postgres:latest
    container_name: strapi-db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./strapi-data:/var/lib/postgresql/data
    ports:
      - "24538:5432"
    networks:
      backend:
        ipv4_address: 192.168.55.20

  traccar:
    image: aneopsy/aitotracker:latest
    container_name: traccar
    env_file: .env
    depends_on:
      - traccar-db
    restart: always
    configs:
      - source: traccar_xml
        target: /opt/traccar/conf/traccar.xml
    volumes:
      - ./logs:/opt/traccar/logs
    ports:
      - 8082:8082
      - 5020:5020/tcp
      - 5055:5055/tcp
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        ipv4_address: 192.168.55.10

  strapi:
    image: elestio/strapi-${NODE_ENV}:latest
    container_name: strapi
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapi-db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      # - ./package.json:/opt/package.json
      # - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      - ./entrypoint.sh:/opt/app/entrypoint.sh
    ports:
      - "8081:1337"
    depends_on:
      - strapi-db
    networks:
      backend:
        ipv4_address: 192.168.55.21

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

configs:
  traccar_xml:
    file: traccar.xml

volumes:
  traccar-db:
    external: true
